
[brick]
authors = "arezaii"
chplVersion = "2.0.0"
license = "None"
name = "gdal"
source = "git@github.com:arezaii/chapGDAL"
type = "library"
version = "0.1.0"

[dependencies]
HelloWorld = "0.1.0"

[system]
gdal = "*"

